version: '3'

services:
  ### CONFIG SERVER REPLICASET
  <FOG_NODE_ID>-cfg-svr1:
    container_name: <FOG_NODE_ID>-cfg-svr1
    image: mongo
    command: mongod --configsvr --replSet cfgrs<FOG_NODE_ID> --port 27017 --dbpath /data/db
    ports:
      - 4<FOG_NODE_ID>1:27017
    networks:
      - fog_sharding
    volumes:
      - <FOG_NODE_ID>_cfg1_data:/data/db
    depends_on:
      - <FOG_NODE_ID>-cfg-svr2

  <FOG_NODE_ID>-cfg-svr2:
    container_name: <FOG_NODE_ID>-cfg-svr2
    image: mongo
    command: mongod --configsvr --replSet cfgrs<FOG_NODE_ID> --port 27017 --dbpath /data/db
    ports:
      - 4<FOG_NODE_ID>2:27017
    networks:
      - fog_sharding
    volumes:
      - <FOG_NODE_ID>_cfg2_data:/data/db
  ### CONFIG SERVER REPLICASET END

  ### SHARD REPLICASET
  <FOG_NODE_ID>-shard-svr1:
    container_name: <FOG_NODE_ID>-shard-svr1
    image: mongo
    command: mongod --shardsvr --replSet shardrs<FOG_NODE_ID> --port 27017 --dbpath /data/db
    ports:
      - 5<FOG_NODE_ID>1:27017
    networks:
      - fog_sharding
    volumes:
      - <FOG_NODE_ID>_shard1_data:/data/db
    depends_on:
      - <FOG_NODE_ID>-shard-svr2

  <FOG_NODE_ID>-shard-svr2:
    container_name: <FOG_NODE_ID>-shard-svr2
    image: mongo
    command: mongod --shardsvr --replSet shardrs<FOG_NODE_ID> --port 27017 --dbpath /data/db
    ports:
      - 5<FOG_NODE_ID>2:27017
    networks:
      - fog_sharding
    volumes:
      - <FOG_NODE_ID>_shard2_data:/data/db
  ### SHARD REPLICASET END

  ### MONGOS
  <FOG_NODE_ID>-mongos:
    container_name: <FOG_NODE_ID>-mongos
    image: mongo
    command: mongos --configdb cfgrs<FOG_NODE_ID>/<FOG_NODE_ID>-cfg-svr1:27017,<FOG_NODE_ID>-cfg-svr2:27017 --bind_ip 0.0.0.0 --port 27017
    ports:
      - 6<FOG_NODE_ID>1:27017
    networks:
      - fog_sharding
    depends_on:
      - <FOG_NODE_ID>-shard-svr1
      - <FOG_NODE_ID>-cfg-svr1
  ### MONGOS END 

networks:
  fog_sharding:
    driver: bridge

volumes:
  <FOG_NODE_ID>_cfg1_data:
    driver: local
  <FOG_NODE_ID>_cfg2_data:
    driver: local
  <FOG_NODE_ID>_shard1_data:
    driver: local
  <FOG_NODE_ID>_shard2_data:
    driver: local